### ISSUE TITLE
0.8.0 Release Blockers

### ISSUE THREAD

**Issue by pfmooney** [mcavage/node-ldapjs#270]
I want to get 0.8 out the door sooner rather than later.
This is a list of issues I want closed prior to release:
- [x] #218 Easier handling of objectGUID queries
- [ ] #214 Update client documentation
- [ ] #209 Update documentation for new server API

If there are other issues folks consider critical, please comment below.

**Comment by flyswatter** [comment]
I would vote for compatibility with node 0.12/io.js.

**Comment by pfmooney** [comment]
@flyswatter That already should be the case in #master.

**Comment by flyswatter** [comment]
Oh, ok, as long as that's the basis of 0.8.0 :+1:

**Comment by pfmooney** [comment]
It assuredly will be.

**Comment by RaviVaranasi** [comment]
Any update on when 0.8 will be released in the wild?

**Comment by pfmooney** [comment]
I've been too busy at work to put much time into this recently.
I do not have an ETA.

**Comment by flyswatter** [comment]
Yaaay!!!! Thank youuuu!!!!

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.
